export const colors = {
  "on-error": "#ffffff",
  "surface-container-lowest": "#ffffff",
  "surface-tint": "#466557",
  "on-tertiary-fixed-variant": "#474743",
  "surface-container-low": "#f6f3f2",
  "on-primary-fixed-variant": "#2f4d40",
  "secondary-fixed": "#ffdbcf",
  "tertiary": "#1a1a18",
  "on-tertiary-fixed": "#1b1c19",
  "surface-container-high": "#eae7e7",
  "surface": "#fcf9f8",
  "on-secondary-fixed-variant": "#793015",
  "surface-container": "#f0edec",
  "tertiary-fixed": "#e5e2dd",
  "on-surface": "#1b1c1b",
  "secondary": "#97472a",
  "charcoal": "#1b1c1c",
  "on-error-container": "#93000a",
  "on-secondary-fixed": "#390c00",
  "surface-container-highest": "#e4e2e1",
  "inverse-primary": "#adcebd",
  "forest-green": "#163428",
  "secondary-fixed-dim": "#ffb59c",
  "on-primary": "#ffffff",
  "surface-bright": "#fcf9f8",
  "error-container": "#ffdad6",
  "surface-variant": "#e4e2e1",
  "on-secondary": "#ffffff",
  "outline-variant": "#c1c8c3",
  "primary": "#001f14",
  "outline": "#727974",
  "secondary-container": "#ff9975",
  "error": "#ba1a1a",
  "on-secondary-container": "#772f14",
  "terracotta": "#97472a",
  "surface-dim": "#dcd9d8",
  "surface-linen": "#fcf9f8",
  "inverse-surface": "#303030",
  "background": "#fcf9f8",
  "tertiary-fixed-dim": "#c8c6c2",
  "tertiary-container": "#2f2f2c",
  "on-surface-variant": "#424844",
  "on-primary-fixed": "#022016",
  "primary-fixed": "#c8ead8",
  "clay-outline": "#727974",
  "on-tertiary": "#ffffff",
  "primary-container": "#163428",
  "on-tertiary-container": "#989692",
  "inverse-on-surface": "#f3f0ef",
  "on-background": "#1b1c1b",
  "error-red": "#ba1a1a",
  "on-primary-container": "#7d9d8d",
  "primary-fixed-dim": "#adcebd"
};

export const typography = {
  bodyMd: { fontFamily: 'HankenGrotesk_400Regular', fontSize: 16, lineHeight: 25.6 },
  labelMd: { fontFamily: 'HankenGrotesk_600SemiBold', fontSize: 14, lineHeight: 19.6, letterSpacing: 0.7 },
  headlineMd: { fontFamily: 'EBGaramond_500Medium', fontSize: 24, lineHeight: 31.2 },
  headlineLg: { fontFamily: 'EBGaramond_500Medium', fontSize: 32, lineHeight: 38.4 },
  displayLg: { fontFamily: 'EBGaramond_500Medium', fontSize: 48, lineHeight: 52.8, letterSpacing: -0.96 },
  bodyLg: { fontFamily: 'HankenGrotesk_400Regular', fontSize: 18, lineHeight: 28.8 },
  labelSm: { fontFamily: 'HankenGrotesk_500Medium', fontSize: 12, lineHeight: 16.8 },
  headlineLgMobile: { fontFamily: 'EBGaramond_500Medium', fontSize: 28, lineHeight: 33.6 },
};

export const spacing = {
  stackLg: 32,
  marginMobile: 16,
  stackSm: 8,
  marginDesktop: 40,
  stackMd: 16,
  containerMax: 1280,
  sectionGap: 80,
  base: 4,
  gutter: 24
};
